package com.mxgraph.model;

public enum CellGapEnum {

    OUTER_TOP_TO_OUTER_BOTTOM,
    OUTER_TOP_TO_INNER_1_TOP,
    OUTER_TOP_TO_INNER_1_BOTTOM,
    OUTER_TOP_TO_INNER_2_TOP,
    OUTER_TOP_TO_INNER_2_BOTTOM,
    INNER_1_TOP_TO_INNER_2_TOP,
    INNER_1_TOP_TO_INNER_2_BOTTOM,
    INNER_1_TOP_TO_OUTER_BOTTOM,
    INNER_1_BOTTOM_TO_INNER_2_TOP,
    INNER_1_BOTTOM_TO_INNER_2_BOTTOM,
    INNER_1_BOTTOM_TO_OUTER_BOTTOM,
    INNER_2_TOP_TO_OUTER_BOTTOM,
    INNER_2_BOTTOM_TO_OUTER_BOTTOM,
}
